geodynamics/burnman

burnman/solidsolution.py
tests/test_solidsolution.py

Squashing was so miserable that I made a new branch.

add molar_mass

---

burnman/chemicalpotentials.py
burnman/data/input_raw_endmember_datasets/slb_2011_solutions.txt
burnman/mineral_helpers.py
burnman/minerals/Murakami_2013.py
burnman/minerals/SLB_2005.py
burnman/minerals/SLB_2011.py
burnman/minerals/SLB_2011_ZSB_2013.py
burnman/minerals/other.py
burnman/solidsolution.py
misc/benchmarks/solidsolution_benchmarks.py
misc/paper_incorrect_averaging.py
misc/paper_onefit.py
misc/pyrolite_uncertainty.py
tests/test_solidsolution.py

Renames *base_material* and *base_materials* to *endmembers*.

rename base_material to endmembers

---

test.sh

This might make it work on MAC.

do not use grep -P

---

examples/example_averaging.py
examples/example_composition.py
examples/example_geotherms.py
examples/example_optimize_pv.py
examples/example_woutput.py
misc/ref/example_averaging.py.out
misc/ref/example_woutput.py.out

Some examples were broken, and in others I just put a more 'modern' rock. I'm aware that this will probably break a bunch of tests as outputs might have changed, but I don't know how to fix this.

modernizing examples

---

burnman/data/input_raw_endmember_datasets/slb_2011_solutions.txt
burnman/data/input_raw_endmember_datasets/tc-ds62_solutions.txt
burnman/mineral_helpers.py
burnman/minerals/HP_2011_ds62.py
burnman/minerals/Murakami_2013.py
burnman/minerals/SLB_2005.py
burnman/minerals/SLB_2011.py
burnman/minerals/SLB_2011_ZSB_2013.py
burnman/minerals/other.py
burnman/solidsolution.py
burnman/solutionmodel.py
examples/example_solid_solution.py
misc/benchmarks/solidsolution_benchmarks.py
misc/paper_incorrect_averaging.py
tests/test_solidsolution.py

The optional argument *molar_fraction* is added to the __init__ of the SolidSolution class. This allows the user to set the [composition] of the solid solution with a single line rather than two. The order of variables is chosen for compatibility with older SolidSolution classes.

Molar fractions and state passed to SolidSolution

---

burnman/eos/hp.py
burnman/minerals/Sundman_1991.py
misc/benchmarks/endmember_benchmarks.py
tests/test_endmembers.py

Adds terms accounting for the magnetic contribution to the Gibbs Free Energy. Important for phases like body centered cubic (BCC) iron.

Magnetic contribution

---

burnman/minerals/HP_2011_ds62.py
burnman/minerals/SLB_2011.py
burnman/solidsolution.py
examples/example_composition.py
examples/example_solid_solution.py
misc/benchmarks/solidsolution_benchmarks.py
tests/test_solidsolution.py

The solution model structure was difficult to read, and some of the parameters used in __init__ were not retrievable after use. This restructuring improves compactness, readability and functionality.

Solution model restructuring

---

examples/example_build_planet.py
misc/paper_averaging.py
misc/paper_benchmark.py
misc/paper_fit_data.py
misc/paper_onefit.py
misc/paper_opt_pv.py
misc/paper_opt_pv_old.py
misc/paper_uncertain.py
misc/paper_uncertainty.py
misc/pyrolite_uncertainty.py
misc/ref/paper_averaging.py.out

In preparation for fixing up whatever test output needs updating by #107

'sanserif' is not a valid font family, 'sans-serif' is.

---

misc/ref/example_optimize_pv.py.out

Update test output changed by #140

Fix test output

---

burnman/eos/hp.py
burnman/tools.py
examples/example_tools.py
misc/ref/example_tools.py.out
tests/test_tools.py
tests/tests.py

It's about time these workhorse functions were added!

Added equilibrium and EoS fitting functions to tools.py

---

burnman/eos/debye.py
burnman/eos/slb.py

This speeds up solving for the volume in slb (which is quite a bottleneck) and the debye function (which just gets called a lot). Not as significant of an improvement to adding properties.

Speed up slb

---

burnman/seismic.py
tests/test_seismic.py
tests/tests.py

- fix fast/slow density
- improve error message if density is not defined
- fix comments
- test!

fix and test seismic

---

burnman/material.py
tests/test_decorators.py
tests/tests.py

- test caching of material_property
- pass through documentation and test that

test and fix material_property

---

misc/paper_averaging.py
misc/paper_fit_data.py
misc/paper_incorrect_averaging.py
misc/paper_onefit.py
misc/paper_opt_pv.py
misc/paper_opt_pv_old.py
misc/paper_uncertain.py
misc/paper_uncertainty.py
misc/pyrolite_uncertainty.py

to work with sphinx and running the files

fix color import

---

burnman/composite.py
burnman/mineral.py
burnman/solidsolution.py

- never set SolidSolution.method to a normal averaging method
- need to set it to something so Mineral won't complain
- call mineral's methods

fix SolidSolution

---

burnman/composite.py
burnman/mineral.py
burnman/solidsolution.py
tests/test_composite.py

Remove try except for mass_to_molar_fractions

---

burnman/eos/debye.py

create env variable to disable jit if wanted

---

burnman/material.py
burnman/seismic.py

- delete return after raise
- raise NotImplementedError where appropriate

remove dead code

---

burnman/version.py
setup.py

- change versioning scheme
- add setup.py classifiers
- modify short/long description

release prep

---

tutorial/step_3.py

Alternative to #216.
What do you think about this, @bobmyhill ?

For silly reasons, this removes a matplotlib warning.

---

burnman/eos/slb.py
burnman/mineral.py

I noticed the code had slowed down (while working on updating the inversion branch), because a couple more volume class snuck in with the modifications to properties. I'm not sure if this is the most elegant way to solve it, so I'm open to suggestions.

Fix number of volume calls

---

tests/test_averaging.py
tests/test_solidsolution.py

catch reuss_average warning
addresses #236

check for warnings in tests

---

.gitignore
test.sh

remove .error files generated from test.sh

---

contrib/CHRU2014/__init__.py
contrib/__init__.py
sphinx/examples.rst

sphinxdoc also needs the ``__init__.py`` files to be able to include the files.

fix paths for sphinx-doc

---

burnman/eos/hp.py
burnman/eos/slb.py
burnman/mineral_helpers.py
burnman/partitioning.py
burnman/processchemistry.py
burnman/seismic.py
burnman/solutionmodel.py
contrib/CHRU2014/__init__.py
contrib/CHRU2014/paper_fit_data.py
contrib/__init__.py
examples/example_build_planet.py
examples/example_chemical_potentials.py
examples/example_compare_all_methods.py
examples/example_fit_data.py
examples/example_geotherms.py
examples/example_inv_murakami.py
examples/example_optimize_pv.py
examples/example_premite_isothermal.py
examples/example_spintransition.py
examples/example_tools.py
examples/example_user_input_material.py
examples/example_woutput.py
misc/colors.py
misc/helper_solid_solution.py
misc/performance.py
misc/table.py
setup.py

- remove dead code
- formatting of comments
- remove unused imports
- minor formatting

cleanup (flake8)

---

burnman/mineral.py

fix grueneisen parameter definition

---

test.sh

- skip ``__init__.py``
- test contrib/CHRU2014 folder

testing improvements

---

test.sh

This makes example_build_planet pass

tests: increase numdiff tolerance

---

contrib/CHRU2014/paper_onefit.py
contrib/ipython/Compute_seismic_velocities_advanced.ipynb
contrib/ipython/Compute_seismic_velocities_beginner.ipynb
contrib/tutorial/step_1.py
examples/example_build_planet.py
examples/example_compare_all_methods.py
examples/example_composition.py
examples/example_inv_murakami.py
examples/example_premite_isothermal.py
misc/pyrolite_uncertainty.py

Apparently we think we can lift a cubic meter of mantle/core. I fixed this unit mistake in various places (unfortunately it is also in our paper).

Fix units of density in various examples

---

burnman/material.py
tests/test_material.py

Useful when using np.meshgrid to create a grid of properties.

Evaluate now takes an n dimensional list of pressures and temperatures

---

burnman/perplex.py
tests/test_perplex.py
tests/tests.py

Fixed perplex grueneisen

---

burnman/minerals/HP_2011_ds62.py
burnman/minerals/SLB_2011.py
burnman/solidsolution.py
examples/example_composition.py
examples/example_solid_solution.py
misc/benchmarks/solidsolution_benchmarks.py
tests/test_solidsolution.py

Made solidsolution attribute naming consistent with constructor variables

---

homepage/download.html
homepage/examples.html
homepage/index.html

Messed this up... pushing it too upstream, but hopefully we can get this update tot the webpage out of the way quickly and git rid of the branch.

homepage update

---

burnman/eos/vinet.py
sphinx/ref.bib

Minor changes to add references to Vinet EoS and remove rogue 'third-order's

added references for Vinet

---

burnman/eos/__init__.py
burnman/eos/helper.py
burnman/eos/reciprocal_kprime.py
sphinx/eos.rst
sphinx/ref.bib
tests/test_eos.py

Adds the equation of state documented by Stacey and Davis (2004). Infinite pressure limits on K' are explicitly included in this equation of state, which allows modeling of high pressure planetary interiors (e.g. Earth's core).

Reciprocal kprime equation of state

---

burnman/eos/birch_murnaghan.py
burnman/eos/birch_murnaghan_4th.py
burnman/eos/modified_tait.py
burnman/eos/morse_potential.py
burnman/eos/vinet.py
sphinx/ref.bib
tests/test_eos.py

added energies to static equations of state

---

burnman/eos/reciprocal_kprime.py
tests/test_eos.py

If there's an analytical solution, it's messy...

Energy calculations for the reciprocal K' EoS

---

burnman/solutionmodel.py

vectorised ideal, symmetric, asymmetric solution models

---

burnman/composite.py
burnman/solidsolution.py
burnman/solutionmodel.py
tests/test_solidsolution.py

For stability in gibbs minimization / equilibrium calculation schemes, it is useful to have analytical expressions for the compositional gibbs hessian (d2G/dxidxj), which is equal to the compositional gradient of the chemical potentials of the endmembers (dmui/dxj).
It is also useful to have the first derivatives of the gibbs hessian with respect to temperature and pressure - the entropy and volume Hessians.
This PR implements these expressions for the ideal, symmetric and asymmetric solution models.
This branch is derived from that in PR #316

Added gibbs, entropy and volume hessian calculations to solid solutions

---

burnman/__init__.py
homepage/index.html
sphinx/index.rst
sphinx/ref.bib

Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).
Cheers!

Link DOIs to preferred resolver

---

Jenkinsfile
test.sh
tests/tests.py

- new testing infrastructure based on https://jenkins.tjhei.info/
- update test script to fail if error is encountered
- add sympy support (and a test for it)

add Jenkins integration

---

burnman/solutionmodel.py
tests/test_solidsolution.py

I rederived the compositional derivatives of the free energy for the subregular solution model. The new expression for the endmember potentials is simplified over the Helffrich and Wood paper. The hessian derivation is also new.

subregular model: added hessian, streamlined endmember potentials

---

burnman/processchemistry.py
tests/test_solidsolution.py

Added formula to string conversion.

added formula to string conversion

---

burnman/__init__.py
burnman/partitioning.py
tests/test_partitioning.py

Reworks the old Nakajima partitioning functions using the new Composition class.
Resolves Issue #297
Requires #336.

Rework partitioning

---

burnman/composite.py
burnman/minerals/SLB_2005.py
tests/test_composite.py

Added molar formula to composite. Also added formulae to endmembers in SLB_2005, and added a test for the new functionality.

added formula to composite

---

contrib/CHRU2014/paper_averaging.py
contrib/CHRU2014/paper_uncertain.py

Addresses version problems raised in #357

removed handle/label calls to matplotlib

---

Jenkinsfile.cig

This tells Jenkins to remove files created by the build.

Add cleanWs to post build step

---

examples/example_spintransition_thermal.py

This PR adds a new spin transition example for finite temperatures.

added new spin transition example

---

burnman/mineral.py
burnman/model.py
burnman/nonlinear_fitting.py
burnman/nonlinear_solvers.py
burnman/output_seismo.py
burnman/partitioning.py
burnman/perplex.py
burnman/planet.py
burnman/processchemistry.py
burnman/seismic.py
burnman/solidsolution.py
burnman/solutionmodel.py
burnman/tools.py

This PR resolves most of the pycodestyle warnings for `mineral.py` through to `version.py` in the main `burnman` directory.

improve code style

---

tests/burnman_path.py
tests/test_anisotropy.py
tests/test_averaging.py
tests/test_chemical_potentials.py
tests/test_composite.py
tests/test_composition.py
tests/test_debye.py
tests/test_decorators.py
tests/test_endmembers.py
tests/test_eos.py
tests/test_eos_consistency.py
tests/test_fitting.py
tests/test_geotherm.py
tests/test_helper_rock_switcher.py
tests/test_material.py
tests/test_minerals.py
tests/test_model.py
tests/test_modifiers.py
tests/test_partitioning.py
tests/test_perplex.py
tests/test_planet.py
tests/test_processchemistry.py
tests/test_seismic.py
tests/test_solidsolution.py
tests/test_solvers.py
tests/test_spin.py
tests/test_tools.py

This PR sanitises the imports in the tests directory.

added burnman_path to tests

---

burnman/composite.py
examples/example_composite.py
misc/ref/example_composite.py.out

This PR adds an example for the Composite class. The example shows how to:
- initialize a composite
- interrogate it for different properties
- use the new properties introduced in #400 to show how to solve simple equilibrium problems (manually defining the unknowns - the general equilibrium class will come later).
It seems we already had a stray output file for an example_composite.py file that was never merged. This PR therefore overwrites that file with something that is actually used.

New example for Composite class

---

burnman/composite.py

This PR converts composite fractions into numpy arrays when they are initially set.

make composite use numpy arrays

---

.github/workflows/main.yml
Readme.md
requirements.txt

- add basic requirements.txt
- update readme
- use requirements.txt in CI

add requirements.txt, use in CI

---

contrib/anisotropic_eos/Readme.md
contrib/anisotropic_eos/cubic_fitting.py
contrib/anisotropic_eos/orthorhombic_fitting.py
contrib/eos_fitting/Readme.md
contrib/eos_fitting/eos_fitting.py
contrib/eos_fitting/read_data.py

Adds readme files to my contributed directories.

Add contrib readmes

---

burnman/classes/composite.py
burnman/tools/chemistry.py
burnman/tools/equilibration.py
docs/changelog/20211030_bobmyhill.rst
examples/example_chemical_potentials.py
misc/benchmarks/chemical_potential_benchmarks.py
tests/test_chemical_potentials.py

This PR:
- adds a chemical potentials method to Composite. 
- adds four new tests of the method
- allows the equilibrium solver to define the equilibrium tolerance (if the solve is successful, by definition the assemblage is at equilibrium).

added chemical_potentials function to composite

---

.binder/environment.yml
.binder/postBuild
contrib/ipython/Create_1D_ASPECT_profile.ipynb

Added binder config files and modified the 1D ASPECT profile notebook. With thanks to @ianhi for showing me the light. 
A separate PR will strip out all of the installation hacks from the project.

Add binder config

---

Readme.md
docs/examples.rst
docs/index.rst

This PR updates the main Readme.md file. It replaces all of the old example text with a brief description of the tutorial, and a link to the documentation for more information.

shorten readme

---

.binder/environment.yml
tutorial/tutorial_01_material_classes.ipynb

Adds pycddlib and cvxpy to the binder environment.yml.

added optional packages to binder env

---

examples/example_anisotropy.py
examples/example_fit_composition.py
tutorial/tutorial_04_fitting.ipynb

This PR addresses two deprecation warnings.

fix matplotlib deprecation warnings

---

burnman/classes/anisotropicmineral.py
burnman/tools/equilibration.py
examples/example_anisotropy.py
examples/example_fit_composition.py
tests/test_anisotropicmineral.py
tutorial/tutorial_04_fitting.ipynb

This PR updates the full_isothermal_stiffness_tensor in AnisotropicMineral so that it uses the existing expansion function (rather than one that doesn't exist).
A new test is added to test the expansion.

Update function call for anisotropic stiffness tensor

---

contrib/CHRU2014/paper_fit_data.py
examples/example_equilibrate.py
misc/ref/paper_fit_data.py.out
setup.py
test.sh

A few minor tweaks to ensure the tester runs successfully on Python 3.10 (burnman installed in a conda environment on Mac M1)

tweaks for python 3.10

---

Readme.md

Added some brief notes about using environment managers (conda / pyenv).

add environment management notes

---

burnman/optimize/eos_fitting.py

Removes some flake8 warnings from eos_fitting.py

improve formatting in eos_fitting

---

burnman/optimize/nonlinear_fitting.py

This PR tidies nonlinear_fitting.py and removes duplicate axis labels for shared labels in corner plots.

improved corner plot

---

Readme.md

Small tweak to the scripting notes to improve English and remove description of deprecated Python (2.x) behaviour.

Update Readme.md scripting notes

---

burnman/classes/anisotropicmineral.py
contrib/anisotropic_eos/orthorhombic_fitting_second_form.py

This PR adds the thermal stress (`d sigma / dT | epsilon`) and isometric heat capacity (`d^2 F / dTdT | epsilon`) to the anisotropic mineral class.

added thermal stress and isometric heat capacity to anisotropic mineral properties

---

burnman/utils/math.py
contrib/solution_polytope/example_solution_creation_and_manipulation.py
misc/ref/example_solution_creation_and_manipulation.py.out

This PR improves the `generate_complete_basis` function in `utils/math` so that the first n rows of the complete basis are the same as the incomplete basis.

improved basis completion

---

.github/workflows/main.yml
Readme.md
burnman/classes/solution.py
burnman/classes/solutionmodel.py
docs/background_solutions.txt
docs/changelog/20220625_bobmyhill.rst
docs/pip_requirements.txt
docs/solution_models.rst
test.sh
tests/test_solidsolution.py
tests/util.py

This PR implements a new type of solution model that takes a user-defined Gibbs free energy function as input. Required derivatives are calculated by the autograd module, which is now added as an optional dependency.

New function solution model

---

burnman/classes/elasticsolution.py
burnman/classes/elasticsolutionmodel.py
docs/changelog/20220625_bobmyhill.rst
docs/solution_models.rst
tests/test_elasticsolution.py

This PR adds the Helmholtz equivalent of the Function solution model implemented in PR #495. Tests and documentation are also added.

added elastic function solution, tests, docs

---

burnman/classes/elasticsolutionmodel.py
tests/test_elasticsolution.py

The partial pressure term in the elastic function solution model had the wrong sign.
This has been fixed, and new tests added.

fix sign of autograd partial pressures

---

burnman/classes/solution.py
burnman/classes/solutionmodel.py
docs/changelog/20221022b_bobmyhill.rst
docs/pip_requirements.txt
setup.py
tests/test_solidsolution.py

This PR adds a new generalised polynomial solution model to BurnMan. The non-ideal excesses in this model are polynomial functions of composition. The coefficients of these polynomials are either constant internal energy, entropy and volume (i.e. Gxs = (Eijk... - T Sijk... + P Vijk...) xi xj xk...) or a linear sum of Mineral objects (i.e. Gxs = amijk mineralm.gibbs ... xi xj xk ...). Coefficients for both of these forms are passed as a list of lists to instantiate a PolynomialSolution object, which can then be passed as usual to instantiate a Solution object.

Polynomial solution model

---

tutorial/tutorial_01_material_classes.ipynb
tutorial/tutorial_03_layers_and_planets.ipynb

This PR addresses #533 and #534

Improve tutorials

---

examples/example_add_shear_modulus.py
misc/ref/example_add_shear_modulus.py.out

This PR adds a new example that demonstrates adding a shear modulus function to an equation of state without one.
Demonstrates potential solutions to #481.

add shear modulus example

---

burnman/optimize/eos_fitting.py
burnman/tools/equilibration.py
burnman/utils/geotherm.py
burnman/utils/misc.py

Fixes for a few deprecation warnings.

np.product->np.prod

---

burnman/classes/anisotropicmineral.py
burnman/classes/material.py
burnman/classes/mineral.py
burnman/tools/eos.py

This PR refactors the anisotropic equation of state in preparation for addition of an anisotropic solid solution class.

refactored anisotropic functions

---

burnman/classes/anisotropicmineral.py

This PR adds a new heat capacity function to the AnisotropicMineral class.

added function for Cv to anisotropic material

---

contrib/anisotropic_plagioclase/plagioclase_data.py
contrib/anisotropic_plagioclase/plagioclase_model.py
contrib/anisotropic_plagioclase/plagioclase_model_plots.py

Minor modifications to the plagioclase solution model contribution. No changes to the core burnman code.

added tabulation for plag contribution

---

burnman/classes/solution.py
burnman/optimize/linear_fitting.py
examples/example_fit_composition.py

See https://www.cvxpy.org/updates/#dropping-ecos-dependency

remove ECOS as default linear solver for cvxpy

---

.github/workflows/coverage.yml

Adds a github action that generates a code coverage report for the tests and compares the coverage with main.

add coverage.yml

---

tests/test_calibrants.py

Adds a test for the pressure_to_pressure Calibrant function

added calibrant P2P test

---

Readme.md
tests/test_eos.py
tests/test_eos_consistency.py
tests/test_polytope.py

Some tests that increase code coverage to 86.35%

added tests

---

Readme.md
burnman/eos/dks_solid.py
burnman/eos/hp.py
burnman/optimize/nonlinear_fitting.py
burnman/tools/output_seismo.py
burnman/utils/misc.py
misc/benchmarks/ab_initio_solids.py
tests/test_eos.py
tests/test_eos_consistency.py
tests/test_fitting.py
tests/test_seismic.py
tests/test_solidsolution.py
tests/test_tools.py

This PR removes unused EoS functions and improves test coverage.

Remove unused functions, improve coverage

---

.github/workflows/coverage.yml
Readme.md
burnman/eos/debye.py
burnman/eos/dks_solid.py
burnman/eos/einstein.py
burnman/eos/macaw.py
burnman/eos/reciprocal_kprime.py
burnman/eos/slb.py
burnman/eos/spock.py

This PR allows numba to not be installed. This also allows testing of jit-decorated functions.

allow numba to be not installed

---

burnman/eos/brosh_calphad.py
tests/test_endmembers.py

removed numerical derivatives in Brosh-Calphad EoS

---

Readme.md
tests/test_layer.py
tests/test_solidsolution.py

This PR adds tests for the evaluate_with_volumes function and for layer properties. Coverage is now >92%.

Improve coverage

---

burnman/classes/material.py
burnman/eos/hp.py
burnman/eos/modified_tait.py
burnman/optimize/eos_fitting.py
burnman/optimize/nonlinear_fitting.py
burnman/utils/misc.py
examples/example_fit_eos_with_independent_volumes.py
misc/ref/example_fit_eos_with_independent_volumes.py.out
tests/test_fitting.py

This PR adds the ability to fit an equation of state based on volume-temperature-property data. Previously, only pressure-temperature-property data could be fitted.

V-T fitting

---

burnman/utils/__init__.py
burnman/utils/plotting.py
contrib/perplex/create_lo_res_table.py
contrib/perplex/create_phase_diagram.py
contrib/perplex/perplex_utils.py
test.sh
tests/test_utils.py

This PR adds the ability to create arbitrarily high-resolution phase diagrams using Perple_X.

added phase diagram creator

---

contrib/perplex/create_phase_diagram.py
contrib/perplex/perplex_utils.py

This PR modifies the PerpleX phase diagram maker to number assemblages which are too small to accept a full assemblage label.

allow numbering for small fields

---

burnman/eos/__init__.py
burnman/eos/anharmonic_debye_pade.py
docs/eos.rst
tests/test_anharmonic.py

This PR modifies the new Anharmonic contribution to equations of state such that the entropy and heat capacity (rather than the Helmholtz energy) are only functions of T/Theta_D.
The documentation has been improved to highlight this choice.

scale anharmonic entropy
