geodynamics/burnman

test.sh

readlink is not supported on mac, but it turns out we don't need it.
Make numdiff optional. Tests will run but some tests will fail using
diff.

test.sh: make numdiff optional, make run on MAC

---

burnman/solutionmodel.py

One line fix to excess_entropy, as the configurational term erroneously included a stray factor of *temperature*.
The bug did not affect any of the main gibbs functions.

Fix entropy expression

---

burnman/solutionmodel.py
examples/example_solid_solution.py
tests/test_solidsolution.py

The activity-composition models currently in burnman are those used by Holland and Powell. These are by far not the only formulations, and indeed Holland and Powell's asymmetric model is somewhat inflexible, especially  when it comes to fitting first derivatives of the Gibbs free energy (like fO2, for example).
The subregular solution model introduces cubic terms to the quadratic regular solution model. It has been used extensively in the thermodynamics literature. A detailed derivation of useful terms can be found in Helffrich and Wood (1989).

Subregular solution model

---

misc/paper_averaging.py
misc/paper_benchmark.py
misc/paper_fit_data.py
misc/paper_incorrect_averaging.py
misc/paper_onefit.py
misc/paper_opt_pv.py
misc/paper_uncertain.py
misc/paper_uncertainty.py
misc/pyrolite_uncertainty.py

The do-nothing `Template` backend appears to be bugged (as far as I can tell) for at least a few versions of matplotlib when using TeX rendering. Since we don't care about the output when running tests, we can just not call savefig().

When running tests, don't call savefig.

---

examples/example_optimize_pv.py

Just noticed that optimize_pv from the paper is still using the old solid solutions. While the example of optimize_pv (in the examples directory) just has a really poor choice of composition. I've tried to update that example here a bit. Please check so I can add the code to our slides.

fix optimize perovskite example

---

test.sh

This caused the test misc/paper_onefit to pass where we swapped values a
long time ago because both numbers where ~1e-7.

remove absolute numdiff tolerance

---

burnman/minerals/HP_2011_ds62.py
examples/example_solid_solution.py

The changes to solid solution rendered the single ss in HP_2011_ds62 out of date. This patch fixes the problem.

Garnet solution model syntax update

---

burnman/endmemberdisorder.py
burnman/eos/hp.py
burnman/eos/slb.py

This patch fixes the volume Landau contribution, removes the double counting of the enthalpy of disorder (oops), and completes the change of references to T_0 in SLB.
There are still changes to make w.r.t. Landau (w.r.t. K_T, K_S), but these can wait until our redesign of excess contributions in December.

Correct landau V, changed SLB references to T_0

---

burnman/eos/birch_murnaghan.py
burnman/eos/equation_of_state.py
burnman/eos/slb.py
tests/test_eos.py

Cleaning up some unneeded functions.
Density is defined in the base class for eos. Here I also passed in volume, so it doesn't get computed again. However, this function currently doesn't get called (mineral, composite and solidsolution have their own equations for density).
SLB just had to functions for pressure. They gave the same solutions, I just picked the quicker one. (Still don't know if the solution is good, do you have a benchmark for this, Ian?)

Rm density from eos

---

burnman/averaging_schemes.py
tests/test_averaging.py

Heidi Fuqua reported a bug where the Reuss function returns zero when one of the shear moduli of the phases is zero, even when that phase is not present (has zero volume fraction). This fixes that case, as well as slightly cleans up the voigt and reuss average functions.

Cleanup voigt and reuss functions

---

burnman/composite.py
burnman/material.py
burnman/mineral.py
burnman/mineral_helpers.py
tests/test_composite.py
tests/test_material.py
tests/tests.py

- create writeable property Material.name and allow overriding it in
Mineral.params
- check that Material.__init__ is called in a couple of places
- call Material.__init__ in derived classes
- rewire Material.to_string to use .name

rework Material.name

---

burnman/eos/equation_of_state.py
sphinx/background_userinputs.txt
sphinx/conf.py
sphinx/examples.rst
sphinx/index_pdf.rst
sphinx/zreferences.rst

- fix references
- remove code documentation from pdf
- remove 2 out of 3 indices from pdf
- cleanup

Documentation fixes

---

burnman/eos/debye.py
burnman/eos/slb.py
misc/performance.py

- jit some functions
- add misc/performance.py with several checks
This patch increases performance from:
4331518 function calls (4024502 primitive calls) in 6.741
seconds
to
3574686 function calls (3263157 primitive calls) in 4.139
seconds

tune performance

---

burnman/main.py

This function never gets used, and only loops over a different (equally unused) function anyway.

remove lost function for attenuation correction

---

burnman/solidsolution.py
burnman/solutionmodel.py
examples/example_solid_solution.py
tests/test_solidsolution.py

Quite often, we want to use the activity of a particular endmember in a solid solution, rather than the excess gibbs free energy. This commit adds two attributes to solidsolution, activities and activity_coefficients, which output the overall activity and the proportion of this value attributable to nonideality.

Added activity functions to solid solution, updated example document

---

burnman/data/input_raw_endmember_datasets/SLBdata_to_burnman.py
burnman/eos/property_modifiers.py
burnman/minerals/HP_2011_ds62.py
burnman/minerals/SLB_2011.py
burnman/solidsolution.py
burnman/solutionmodel.py
examples/example_gibbs_modifiers.py
examples/example_solid_solution.py
misc/benchmarks/solidsolution_benchmarks.py
tests/test_modifiers.py
tests/test_solidsolution.py

A minor cosmetic tweak for clarity...
I was reminded recently of a point of contention wrt excess properties. It is conventional to describe excess properties in terms of an excess enthalpy, so I originally formulated the models in terms of excess enthalpy, entropy and volume at 0 K, 0 Pa. This is correct, but for the case of a model where Gex = a - bT + cP, it is clearer to use energy in place of enthalpy - then there's no need to declare the reference state, as G = E - TS + PV. It also makes the code a little easier to understand. See, for example, the excess_enthalpy function in solutionmodel.py.
As this PR changes the front-end naming convention for excess properties, the change should be included in Release 1.0.

Changed excess_enthalpy references to excess_energy for clarity

---

burnman/minerals/HP_2011_ds62.py
burnman/minerals/SLB_2011.py
burnman/solidsolution.py
examples/example_solid_solution.py

constructor for SolidSolution now takes all arguments required to make the implemented SolutionModels. A class is no longer required to create a new SolidSolution instance.
Almost backwards compatible. The only change is that any calls to __init__ with only the molar_fractions parameter now need to name the variable, i.e.:
`burnman.SolidSolution.__init__(self, molar_fractions)`
should now read
`burnman.SolidSolution.__init__(self, molar_fractions=molar_fractions)`

fixed solid solution constructor

---

misc/ref/example_build_planet.py.out
test.sh

this output seems to randomly break, so remove it.

remove example_build_planet residual output for testing

---

burnman/eos/property_modifiers.py
tests/test_averaging.py
tests/test_solidsolution.py

The sign choices in the Landau model coding were unclear, with G_disordered, S_disordered and V_disordered actually corresponding to the energy/entropy/volume of *ordering*. This isn't a bug, as the values were treated appropriately in the relevant expressions. However, it was unclear.
The new shear modulus raised some warnings in the tests, which have now been caught.

Sign changes and catch warnings

---

burnman/perplex.py

The latest version of PerpleX has changed the ordering of P and T. This PR adds a check to ensure that pressure and temperature are read correctly. It also attempts to replace NaNs from the PerpleX tables via interpolation using pandas (if it is installed).

Added flexibility and NaN processing to reading of PerpleX tables

---

burnman/solidsolution.py
tests/test_eos_consistency.py

Well, this is embarrassing. It seems no-one ever tried to calculate Helmholtz or internal energy for a solid solution, and both were implemented incorrectly. This PR fixes the errors and adds the appropriate test.
minerals and materials have always been implemented correctly.

Fix solution potentials

---

burnman/combinedmineral.py
burnman/eos/helper.py
tests/test_solidsolution.py

The CombinedMineral class was derived in such a way that when included in a solid solution, it would lose its method. This PR makes the class more like the other minerals, with a method set using the equation_of_state param and burnman/eos/helper.py.

Enabled combined minerals to be used in solid solutions

---

burnman/__init__.py
burnman/eos/mie_grueneisen_debye.py
burnman/geotherm.py
burnman/layer.py
burnman/material.py
burnman/planet.py
burnman/seismic.py
examples/example_build_planet.py
examples/example_layer.py
misc/ref/example_build_planet.py.out
misc/ref/example_layer.py.out
misc/ref/example_seismic.py.out
tests/test_planet.py

In this pull request (an updated version of PR #302), Sanne did the following:
- Split up Layer and Planet. This is useful in terms of mixing and matching, or in cases where we don't want to model a whole planet.
- Properties are cached within layers
- Parts of the planet can be assigned non-self-consistent pressures.
- The Bullen parameter and Brunt-Vasala frequency can be evaluated within each layer. 
- Adiabatic and perturbed-adiabatic temperature profiles are implemented
- Both Layer and Planet can evaluate all the properties that are also in a Material
Things that can be implemented going forward:
- A perturbed_adiabatic temperature_mode has been implemented. In future we could implement functions in geotherm to approximate boundary layers. 
- The seismic output routines for Mineos …

Planets and layers

---

Readme.md

Hello, and thanks for publishing this :-)
Because the citation info is currently only on the website, I thought it might help users to also find it here.
Or should [10.1002/2013GC005122](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1002/2013GC005122) be cited primarily?
Cheers!

Promote DOI

---

burnman/minerals/ICL_2018.py
burnman/minerals/__init__.py

EoS parameters for the outer core, derived from normal modes. These also have potential use for modelling other planetary cores. 
(I would like to use this for the cider practical)

adding EPOC results

---

burnman/nonlinear_solvers.py
tests/test_solvers.py

Building on PR #315, this PR implements bounds-walking for the affine invariant newton solver. 
Instead of terminating if the Newton descent path leads outside the feasibility region, the solver now uses the method of Lagrangian multipliers to 
minimize `||F(x_i) + J(x_i) dx||`
subject to `C(x_i + dx) = 0`
where `C(x_i + dx)` are the constraints for the solver to walk along. 
I've added some more tests. Because this method only works for constraints which are linear in the parameters `x`, I've removed the ability to pass arbitrary constraint functions to the solver.

Implement bound-walking for the non-linear solver

---

burnman/processchemistry.py

@sannecottaar asked whether dictionarize_site_formula was needed. It isn't used at all, and I don't actually see a use-case for it, given the freedom we've given the site formulations (to allow for different oxidation states, vacancies etc.
Removed in this PR.

removed dictionarize_site_formula

---

burnman/tools.py
misc/benchmarks/ab_initio_liquids.py
misc/benchmarks/liquid_iron_comparison.py
misc/ref/ab_initio_liquids.py.out
misc/ref/liquid_iron_comparison.py.out

The EoS consistency checker has been changed so that the user can choose whether to include shear properties in its list of things to check. This is turned on by default.

added including_shear_properties boolean for eos consistency check

---

burnman/mineral.py
burnman/minerals/Sundman_1991.py
burnman/minerals/__init__.py
misc/ref/table.py.out
tests/test_eos_consistency.py

The grueneisen parameter in burnman is a dependent property, and can therefore be modified by the property_modifiers. This PR fixes that issue. 
Sundman_1991.py is also updated in order to test this fix.

grueneisen parameter now modified by modify_parameters

---

docker/burnman-buildenv-bionic-python2/Dockerfile
docker/burnman-buildenv-bionic-python2/README.md
docker/burnman-buildenv-bionic-python3/Dockerfile
docker/burnman-buildenv-bionic-python3/README.md

I used `test.sh` to make sure the dependencies were correct. The installation guide didn't mention the python sympy library, but `test.sh` complained about not being able to import it. Is that just a `test.sh` dependency?

Create build environment Dockerfiles

---

burnman/eos/dks_liquid.py

scipy version 1.3.0+ moved factorial from scipy.misc to scipy.special. This change will attempt to pull from misc (for older versions) and fall back to special.

fixed scipy's factorial import issue

---

burnman/anisotropy.py
burnman/eos/dks_liquid.py
burnman/nonlinear_fitting.py

numpy and scipy continue to improve, and this is leading to a few function moves / deprecation warnings. The following line changes keep burnman up to date.

avoid deprecation warnings

---

burnman/solidsolution.py

The SolidSolution class uses a dummy class from which an empty object was instantiated as a method attribute. The internal dummy class meant that solutions could not be pickled/dilled.
This attribute only has to be not None in order for everything to work (explicitly set_state), so in this PR I've just replaced the dummy class and instantiation with a string.

Make SolidSolution instances picklable

---

test.sh

Sometimes burnman functionality is highly dependent on the versions of modules used. This PR adds print statements at the start of test.sh so that the user can easily find out which version numbers the tester is using.
Useful output requires that pip be installed as a python module.

test.sh now prints modules version numbers

---

burnman/anisotropy.py
burnman/eos/debye.py
burnman/eos/einstein.py
burnman/nonlinear_fitting.py
burnman/seismic.py
burnman/solidsolution.py
burnman/solutionmodel.py
contrib/CHRU2014/paper_fit_data.py
contrib/eos_fitting/eos_fitting.py
contrib/tutorial/step_3.py
examples/example_build_planet.py
examples/example_fit_data.py
examples/example_fit_eos.py
examples/example_layer.py
examples/example_seismic.py
misc/benchmarks/debye.py
misc/benchmarks/endmember_benchmarks.py
misc/ref/endmember_benchmarks.py.out
misc/ref/example_build_planet.py.out
misc/ref/example_fit_data.py.out
misc/ref/example_layer.py.out
misc/ref/example_seismic.py.out
misc/ref/paper_fit_data.py.out

This PR builds on #375, and removes deprecation warnings related to the release of numpy 1.20.0: https://numpy.org/devdocs/release/1.20.0-notes.html

 updated files to work with python 3.9.2

---

burnman/nonlinear_fitting.py
burnman/seismic.py
burnman/solidsolution.py
burnman/solutionmodel.py
contrib/CHRU2014/paper_fit_data.py
contrib/tutorial/step_3.py
examples/example_build_planet.py
examples/example_fit_data.py
examples/example_layer.py
examples/example_seismic.py
misc/benchmarks/debye.py
misc/benchmarks/endmember_benchmarks.py
misc/ref/endmember_benchmarks.py.out
misc/ref/example_build_planet.py.out
misc/ref/example_fit_data.py.out
misc/ref/example_layer.py.out
misc/ref/example_seismic.py.out
misc/ref/paper_fit_data.py.out

This PR updates files to work with python 3.8.5. There are several changes here:
- Warning messages have changed their syntax, so I've explicitly caught the warnings and printed their messages, rather than allowing python to print the messages itself. This should ensure version and system independent behaviour
- A couple of try/excepts were causing problems for the new warning messages. I've modified these so that they aren't bare excepts any more.
- numba/jit fallback is deprecated. We actually fell back to object mode for most of the asymmetric model jitted functions, because they use numpy functionalities which are not "jittable". As these function were vectorised anyway, I've just removed the jit decorations. This should not cause any significant slowdown for large jobs, and for small …

updated files to work with python 3.8.5

---

examples/burnman_path.py
examples/example_anisotropy.py
examples/example_averaging.py
examples/example_beginner.py
examples/example_build_planet.py
examples/example_chemical_potentials.py
examples/example_compare_all_methods.py
examples/example_composite_seismic_velocities.py
examples/example_composition.py
examples/example_dataset_uncertainties.py
examples/example_fit_data.py
examples/example_fit_eos.py
examples/example_geodynamic_adiabat.py
examples/example_geotherms.py
examples/example_gibbs_modifiers.py
examples/example_grid.py
examples/example_inv_murakami.py
examples/example_layer.py
examples/example_optimize_pv.py
examples/example_perplex.py
examples/example_premite_isothermal.py
examples/example_seismic.py
examples/example_seismic_travel_times.py
examples/example_solid_solution.py
examples/example_spintransition.py
examples/example_tools.py
examples/example_user_input_material.py
examples/example_woutput.py
examples/example_writeout_for_synthetic_seismo.py

This PR removes the ugly hack adding the local burnman path to each of the example files, and instead puts it in its own file. This makes the preamble of all the files cleaner, but doesn't change the functionality in any way.

moved path hack to own file in examples directory

---

burnman/nonlinear_fitting.py

This PR gives the corner plot a sensible size and makes sure labels don't overlap the plots.

neaten corner plot

---

burnman/perplex.py
burnman/planet.py

A couple of minor fixes to:
- allow PerpleX table creator to run with Python 3.8
- Allow the created tables to be interpolated even if they have NaNs in the corners/edges.
- allow Planet to accept PerpleX materials.
- allow two adjoining layers to have adiabatic profiles *and* a temperature jump at the boundary.

minor improvements to perplex and planet

---

burnman/composite.py
burnman/material.py
burnman/processchemistry.py
burnman/reductions.py
tests/test_composite.py

This PR adds Composite properties which correspond to the stoichiometric matrix and associated column, row and nullspaces. These are useful for equilibrium calculations. 
This PR requires use of the pivots from Gaussian elimination. The necessary functions from sympy have been changing very quickly recently. For this PR, those functions are copied into reductions.py. We should be able to remove this code when sympy settles down. 
Secondly, the calculations are relatively expensive and rely on some optional parameters being set. For this reason, we only want to calculate the matrices once when they are first required, and then store the properties forever (i.e. we don't want to have to recalculate them every time we set_state or set_fractions). For this reason, I've also added a …

added stoichiometric matrix and associated properties to Composite

---

burnman/nonlinear_fitting.py
contrib/CHRU2014/paper_incorrect_averaging.py
contrib/CHRU2014/paper_opt_pv.py
contrib/ipython/Create_1D_ASPECT_profile.ipynb
examples/example_anisotropy.py
examples/example_geodynamic_adiabat.py
examples/example_spintransition_thermal.py
misc/benchmarks/property_modifier_benchmarks.py

The tester is failing on at least one benchmark, apparently associated with use of plt.tight_layout().
I think this is related to an old Agg renderer warning that we deal with in test.sh. Presumably the message has changed, but the warning is still there.
This PR replaces the calls to tight_layout() with calls to set_tight_layout(True), which apparently isn't associated with the same warning.

remove tight_layout

---

sphinx/changelog/20210802_burnman_team.rst
sphinx/changelog/20210804_bobmyhill.rst
sphinx/changelog/20210805_bobmyhill.rst
sphinx/changes.rst
sphinx/index_pdf.rst

This PR adds a changelog to the pdf version of the documentation. 
Unfortunately, it seems that globbing is allowed in toctrees, but not includes, so we can't easily add a changelog to the html docs if we're using >1 file to store the changes (which is desirable to avoid version control issues).

added changelog to docs

---

burnman/anisotropy.py
examples/example_anisotropy.py
tests/test_anisotropy.py

This PR changes the names of the properties in AnisotropicMaterial to be more explicit that the properties are isentropic properties, rather than isothermal ones.
This change is required for when we add P-T dependence to the AnisotropicMaterial.

add isentropic qualifier to AnisotropicMaterial

---

burnman/mineral.py
misc/ref/endmember_benchmarks.py.out
tests/test_modifiers.py

In cases where the SLB dataset has a modified volume (e.g. quartz, which has a Landau transition with non-zero volume of disorder), Mineral needs to use the unmodified volume to calculate all of the unmodified properties, and then amend those with the modified properties.
This PR ensures that we do this correctly, and adds two more tests.

fix modified properties with pvt eos

---

.binder/environment.yml
.binder/postBuild

This PR moves installation of mpl-interactions into environment.yml and removes it from postBuild, as suggested in #447.

modify binder installation order

---

tutorial/tutorial_01_material_classes.ipynb
tutorial/tutorial_02_composition_class.ipynb
tutorial/tutorial_03_layers_and_planets.ipynb
tutorial/tutorial_04_fitting.ipynb
tutorial/tutorial_05_equilibrium.ipynb

This PR streamlines the start of each of the tutorials. Now that we require BurnMan to be installed, we no longer need any of the path hacks.

remove old import hacks from tutorials

---

burnman/classes/composite.py
tests/test_chemical_potentials.py

The chemical_potential method in Composite currently reads in a list of formula dictionaries and defines a mapping from endmember amounts to components via least squares. This is quite expensive. 
In most applications, users will only want to define components once. Therefore, it makes sense to create a set_components method that runs through the least squares procedure and stores the component_array as an attribute. The chemical_potential function can then use this attribute to calculate the chemical potential(s).
This PR adds the necessary functions, and modifies a pre-existing test to test the new functionality.

allow storage of components in Composite

---

.binder/environment.yml
setup.py
test.sh

The new binder environment means that we can now migrate the optional dependencies outside of setup.py (into test.sh and .binder/environment.yml).

migrate optional dependencies

---

docs/pip_requirements.txt

This PR adds jupyter to the sphinx dependencies to allow ReadTheDocs to work.

added jupyter to sphinx dependencies

---

burnman/__init__.py
burnman/calibrants/Decker_1971.py
burnman/calibrants/__init__.py
burnman/calibrants/tools.py
burnman/classes/__init__.py
burnman/classes/calibrant.py
docs/changelog/20220128_bobmyhill.rst
docs/examples.rst
docs/materials.rst
docs/mineral_database.rst
examples/example_calibrants.py
misc/ref/example_calibrants.py.out
setup.py

This PR adds a new Calibrant class to BurnMan. This class is a stripped-down version of a Material that is initialised with a params dictionary and a function to compute the pressure or volume at given conditions.
Objects derived from this class have the ability to output pressure/volume as a function of volume/pressure and temperature. The user can pass a V-T or P-T covariance matrix as an additional optional argument, in which case BurnMan will propagate the errors and output a full P-V-T or V-P-T covariance matrix.
A helper function is provided to convert from pressure calculated using one calibration into pressure calculated using another calibration of the same material.
This class is expected to be used by experimental petrologists and those interpreting high pressure experimental …

New: Calibrant class

---

burnman/optimize/eos_fitting.py
burnman/optimize/nonlinear_fitting.py
docs/changelog/20220205_bobmyhill.rst
tests/test_fitting.py

The EoS fitting functions now have additional (optional) arguments. delta params allows the user to set initial values for the change in parameters (i.e. initial step size). bounds allows the user to set hard bounds on the values of each of the parameters.
A new test is added to the test suite.
This PR addresses #328.

Add fitting bounds and deltas

---

burnman/classes/material.py
docs/changelog/20220216b_bobmyhill.rst
tests/test_material.py
tests/test_solidsolution.py

This PR adds a new method to the Material classes called set_state_with_volume that sets state using volume and temperature rather than pressure and temperature.
Two additional tests have been added to check functionality.

added set_state_with_volume function

---

burnman/classes/composition.py
examples/example_composition.py
tests/test_composition.py

This PR simplifies the composition class by removing separate renormalization values for the weight, molar and atomic composition attributes. 
This means that when the user renormalizes the composition, they renormalize the stored composition for the object, rather than a stored renormalization value for the given unit type. This removes confusing behaviour and provides additional functionality (the user can more easily see how many moles of X there are in Y grams of the composition, for example).
This PR does have a small effect on existing behaviour when renormalize is used, but this never affects the ratios of components/elements; only their absolute amounts, and only when not defined by the user.

simplified composition class

---

burnman/classes/anisotropicmineral.py
contrib/anisotropic_eos/tools.py

This PR extends the new AnisotropicMineral so that it can accept a function that computes the Psi tensor and its derivatives as a function of f, Pth and the anisotropic parameters object.
The code is backwards compatible; there is no change to existing functionality.

allowed AnisotropicMineral initialisation with functions

---

burnman/eos/slb.py
tests/test_material.py

This PR improves the root-finding inside the slb volume function. 
It now checks for places where the bulk modulus goes to zero, which results in a minimum of the pressure at a given temperature. If the user has selected a lower pressure, an exception is raised. Otherwise a bracket is found which is consistent with the minimum pressure bound.
This PR also tidies the slb.py file.

Improve slb root finding

---

requirements.txt

This PR adds numba to the pip requirements.txt file to ensure correct numpy dependencies. 
This also preserves the old tester output. Upgrading to numpy 1.23.0 (inconsistent with numba) negligibly degrades the fit_solution.py results (down at 8th decimal point in goodness of fit), but changes the rounded numbers in the covariance matrix sufficiently to cause the tester to fail. Not a bug, so not worthy of raising an issue, but we will probably need to deal with this when numba is updated.

added numba to pip reqs file

---

burnman/__init__.py
burnman/classes/__init__.py
burnman/classes/elasticsolution.py
burnman/classes/elasticsolutionmodel.py
docs/changelog/20211003_bobmyhill.rst
docs/changelog/20220624_bobmyhill.rst
docs/materials.rst
docs/solution_models.rst
docs/tools.rst
examples/example_elastic_solution.py
misc/ref/example_elastic_solution.py.out
tests/test_elasticsolution.py
tests/test_solidsolution.py

This PR implements the elastic solution model detailed in Myhill (2018; https://link.springer.com/article/10.1007/s00410-017-1436-z) as a new class `burnman.ElasticSolution`. This class defines excess thermodynamic properties of solutions relative to the properties of the solution endmembers at fixed volume and temperature, rather than at fixed pressure and temperature. Thus, the models are most easily expressed through parameterisations of the Helmholtz energy, rather than the Gibbs energy.
Elastic solution models mirror those already implemented for the `burnman.Solution` class.
This PR includes the new classes, a new example file, 16 new tests, and associated documentation.

New elastic solution classes

---

burnman/classes/elasticsolution.py
burnman/classes/elasticsolutionmodel.py
burnman/classes/solutionmodel.py
tests/test_elasticsolution.py
tests/test_solidsolution.py

This PR slightly modifies the new `FunctionSolution` and `ElasticFunctionSolution` classes so that configurational entropies are calculated using the existing `logish()` function, rather than `autograd.numpy.log()`. This ensures consistency with other solution models.

use logish in new function solutions

---

tutorial/tutorial_04_fitting.ipynb

This PR slightly reformats the Martian phase proportions figure in Tutorial 4, and removes a stray percentage sign.

correct typo in tutorial figure

---

burnman/classes/composite.py
burnman/tools/chemistry.py
burnman/utils/chemistry.py
docs/changelog/20221003_bobmyhill.rst
tests/test_tools.py

This PR:
- Migrates `reaction_matrix_as_strings` from a method of `Composite` into `utils.chemistry`
- Uses this function in two new helper functions in `tools.chemistry`: `reactions_from_stoichiometric_matrix` and `reactions_from_formulae`, which generate a complete list of reactions (forward and reverse) from either the stoichiometric matrix (a 2D numpy array containing the amount of component j in phase i), or from a list of formulae (as strings or dictionaries of elemental amounts).
New tests are provided.

added new reaction calculator

---

burnman/__init__.py
burnman/classes/combinedmineral.py
burnman/classes/elasticsolution.py
burnman/classes/elasticsolutionmodel.py
burnman/classes/solution.py
burnman/classes/solutionmodel.py
burnman/minerals/HGP_2018_ds633.py
burnman/minerals/JH_2015.py
burnman/minerals/KMFBZ_2017.py
burnman/minerals/SLB_2011.py
burnman/tools/solution.py
contrib/solution_polytope/create_FMS_pyroxene_ordering_figure.py
docs/changelog/20221022_bobmyhill.rst
examples/example_composite_seismic_velocities.py
examples/example_elastic_solution.py
examples/example_solution.py
examples/example_spintransition_thermal.py
misc/benchmarks/solidsolution_benchmarks.py
tests/test_elasticsolution.py
tests/test_solidsolution.py
tutorial/tutorial_01_material_classes.ipynb

This PR removes a series of optional arguments to the Solution class `__init__` function and replaces them with a solution_model argument, that takes a SolutionModel object.
This change introduces backwards-incompatibility, but it allows for the development of more SolutionModel types without having to add useless parameters to the Solution class `__init__` function.

sanitised solution init

---

burnman/eos/debye.py
burnman/eos/einstein.py
burnman/eos/property_modifiers.py
docs/changelog/20221023_bobmyhill.rst
tests/test_modifiers.py

In this PR:
- Four new property modifier formulations are provided, which can be specified with the names "debye", "debye_delta", "einstein" and "einstein_delta". These are based on the Debye and Einstein models of thermal energy. The heat capacity ("debye", "einstein") or entropy ("debye_delta", "einstein_delta") are based on the heat capacity of the respective thermal model, and so reach a maximum at high temperature. The excess energy, entropy and heat capacity are all zero at 0 K. The excess volume is always zero.
- The Einstein thermal energy at 0 K is set to zero. This has no effect on any equations of state, which all use the relative thermal energy.

added new modifiers

---

burnman/classes/anisotropicmineral.py
burnman/tools/eos.py
contrib/anisotropic_eos/orthorhombic_fitting.py
contrib/anisotropic_eos/orthorhombic_fitting_second_form.py

This PR replaces the numerical derivative used to calculate dPthdf in the anisotropic eos with the analytical equivalent.

used analytical derivative in anisotropic eos

---

burnman/eos/slb.py

This PR relaxes the SLB EoS warnings for the Grueneisen parameter and associated power law exponent. Turns out some minerals are weird.

loosened gr_0 and q_0 warnings for SLB model

---

burnman/classes/material.py
tests/test_eos.py

This PR adds a try/except to Material.set_state_with_volume that ensures that the root finding procedure doesn't fail just because brentq tries a pressure that is outside the range of validity of the EoS.
The tweak causes one of the existing tests to fail (because it was designed to test the failure case!). That test has now been replaced with one that would have previously failed.

Improve set_state_with_volume

---

burnman/classes/perplex.py

PerpleX 7.x has slightly changed the functionality and expected user input of werami. This PR alerts the user to the following things they must now do to prepare their directory before running the burnman.perplex.create_perplex_table():
- run vertex
- set sample_on_grid to F in the perplex option file if they want to use the default P-T range
The code itself is reformatted slightly to allow easier processing of the stdout from werami.
This PR is a first step toward addressing #524. 
The code works with Perple_X release 7.0.9.

added useful PerpleX messages

---

.readthedocs.yaml
docs/conf.py
docs/materials.rst
docs/pip_requirements.txt

ReadTheDocs integration will soon only work with a yaml file. 
This PR adds the required file, and makes a couple of other changes required to continue using sphinx / ReST.

add .readthedocs.yaml

---

burnman/tools/chemistry.py
examples/example_reactions.py
misc/ref/example_reactions.py.out

This PR demonstrates the use of the dependent reactions calculator. 
A new example is added. The `reactions_from_stoichiometric_matrix()` function has been tweaked to allow either an array or sympy matrix as argument.

add reactions example

---

burnman/eos/cork.py
tests/test_eos_consistency.py

Addresses #560. Includes a new test for CORK EoS consistency

added derivatives for the CORK EoS

---

burnman/tools/polytope.py
tests/test_polytope.py

preserve composition of solutions when simplifying composites

---

burnman/tools/polytope.py

The `simplify_composite_with_composition()` function can automatically create new solutions with new endmembers. This PR makes sure that the names are useful, by incorporating the site occupancies.

give simplified endmembers useful name

---

burnman/classes/material.py
burnman/classes/mineral.py
burnman/classes/solution.py
burnman/classes/solutionmodel.py
burnman/tools/eos.py

This PR adds an `equilibration_function` argument to the check_eos_consistency functions. This is so that equation of state consistency can be checked for solution model instances where there are explicit isochemical degrees of freedom (such as for order-disorder processes) that allow for relaxation of second-derivatives of the thermodynamic potentials (e.g. alphas, betas, heat capacities).
Implementation of these dynamic equations of state is coming in a future PR.

add internal equilibrate routine to check_eos_consistency functions

---

burnman/classes/solution.py

Minor reformatting to `classes/solution.py`.

reformatted solution

---

burnman/classes/solutionmodel.py
tests/test_solidsolution.py

This PR improves the PolynomialSolution by:
- Changing the user input to give indices and exponents, rather than repeated indices for higher powers
- Internally changing the first and second derivative calculations to be much more efficient and work quickly for high exponents.
- Adding several tests, which would have caught a previously uncaught bug in the second derivative calculations
This PR is a breaking change, as it changes the behaviour of PolynomialSolution.

FIX: improve and fix PolynomialSolution

---

burnman/classes/anisotropicmineral.py
burnman/tools/plot.py
contrib/anisotropic_eos/cubic_fitting_second_form.py
contrib/anisotropic_eos/cubic_fitting_second_form_atherm.py
contrib/anisotropic_eos/cubic_fitting_second_form_only_therm.py
contrib/anisotropic_eos/orthorhombic_fitting_second_form.py

This PR asserts that Phi=0 in anisotropic minerals at standard state.
Also fixes a new bug in anisotropic properties plotting arising from an update to matplotlib (which now scales polar plots to the largest tick value).

assert Phi=0 at standard state

---

burnman/utils/math.py
tests/test_tools.py

Added utility function to check matrix for positive definiteness.

added check for matrix positive definiteness

---

burnman/classes/anisotropy.py
tests/test_anisotropy.py

This PR makes better use of np.einsum to calculate anisotropic properties in a number of directions at the same time.

vectorize anisotropy functions

---

burnman/tools/plot.py
examples/example_anisotropic_mineral.py

This PR makes three improvements to the `tools.plot.plot_projected_elastic_properties()` function:
- Vectors are now drawn to show the directions of particle motion in Vs plots.
- Minimum and maximum Poisson ratios are added as additional plotting options, with vectors representing the lateral directions.
- Where both VS1 and VS2 or Minimum and Maximum Poisson ratios are plotted together, the colourbar takes vmin/vmax from the combined range of values.

improve anisotropic plotting

---

burnman/classes/anisotropicmineral.py
burnman/optimize/eos_fitting.py
burnman/tools/equilibration.py

In a couple of places in the code, `K_T` is used, but this is just an alias for `isothermal_bulk_modulus_reuss`.
This PR removes the use of the aliases in the code, as they are only meant to be convenience functions for the user.

replace K_T

---

burnman/classes/material.py
tests/test_averaging.py
tests/test_solidsolution.py

This PR enables the user to pass an array of molar fractions to the evaluate method, so that solid solutions can be interrogated at a range of compositions. The method can now also be used to return higher order tensor output.

allow evaluation with varying composition

---

burnman/__init__.py
burnman/classes/anisotropicsolution.py
burnman/classes/solution.py
burnman/tools/solution.py
burnman/utils/math.py
tests/test_solidsolution.py

This PR adds new Solution classes that internally minimize the Gibbs energy over user-defined compositional vectors. This can be useful, for example, to determine the equilibrium state of order in a phase, or the relative amounts of high and low spin iron.
Second derivatives of the Gibbs energy are recalculated to take the relaxation into account.

added relaxed solutions

---

burnman/__init__.py
burnman/classes/anisotropicmineral.py
burnman/classes/anisotropicsolution.py
tests/test_anisotropicsolution.py

This PR tests the new RelaxedAnisotropicSolution class, adds some docstrings and fixes the index ordering for a couple of properties.

added anisotropic relaxation

---

burnman/classes/anisotropicmineral.py
burnman/utils/unitcell.py
tests/test_anisotropicmineral.py
tests/test_anisotropicsolution.py
tests/test_anisotropy.py

This PR makes the functions `utils.unitcell.cell_parameters_to_vectors()` and `utils.unitcell.vectors_to_cell_parameters()` more flexible by adding an additional argument `frame_convention`. This required argument takes a list of three integers that define the order of axes and vectors.
The convention dictates that the c[0]th cell vector is colinear with the c[0]th-axis, the c[1]th cell vector is perpendicular to the c[2]th-axis, and the c[2]th cell vector is defined to give a right-handed coordinate system. In common crystallographic shorthand, $x_{c_0}$ // $a_{c_0}$, $x_{c_2}$ // $a_{c_2}^*$.
The new argument is set to be required, as there is no "default" option for non-orthotropic materials - different conventions are more suitable for different materials.

added required frame_convention argument to cell parameter conversions

---

burnman/classes/material.py

This PR:
- Sets the composition before setting state inside `Material.evaluate()`. 
- Restores the original composition after evaluate, if it was already set.

set first composition in evaluate

---

burnman/classes/anisotropicmineral.py
burnman/classes/anisotropicsolution.py
burnman/utils/unitcell.py

This PR allows AnisotropicMineral and AnisotropicSolution to take advantage of the new flexibility in the cell parameter conversion functions in `utils.unitcell` without requiring additional input from the user.

add frame_conventions to AnisotropicSolution

---

.github/workflows/main.yml
burnman/classes/polytope.py
burnman/tools/chemistry.py
burnman/tools/polytope.py
examples/example_polytopetools.py
pyproject.toml
test.sh

The update of pycddlib to Version 3 comes with several improvements:
- a standalone package (pycddlib-standalone) for float representations of polytopes that doesn't require non-python dependencies that can be difficult to install
- a separation of float and fraction modules that makes it easier to type check.
- several new convenience functions.
One downside of the new version is that the old github workflow for installation of the full pycddlib is broken, and I can't figure out how to make the necessary changes.
In this PR, I've added pycddlib-standalone as a dependency, and changed the polytope functions to allow either pycddlib-standalone or the full pycddlib module. If cdd.gmp (the Fractions module) is not found, any calculations that would have used that module instead use cdd (the …

enable pycddlib3

---

burnman/calibrants/Anderson_1989.py
burnman/calibrants/Dorogokupets_2007.py
burnman/calibrants/__init__.py
misc/benchmarks/calibrant_benchmarks.py
misc/ref/calibrant_benchmarks.py.out

Added new calibrants and associated benchmarks. Small differences in DO2007 pressures almost certainly due to rounding of parameters in the published paper.

added Anderson (1989) and Dorogokupets and Oganov (2007) calibrants

---

burnman/calibrants/Decker_1971.py
burnman/eos/birch_murnaghan_4th.py
burnman/eos/modified_tait.py

This PR fixes the internal pressure calculations for the BM4 and Modified Tait equations of state by using the correct versions of V/V0 or V0/V. 
Although these functions have been used in the code for a long time, the error was internally corrected by the use of brentq.

fix BM4, MT pressure calcs

---

burnman/eos/spock.py

This PR replaces the upper incomplete gamma function used by SPOCK with the generalised incomplete gamma function, and replaces `a==0` in the integer checking with `np.abs(a) < 1.e-12`. This improves performance.
The PR also improves the warnings raised by the equation of state for unexpected parameter values.

tweak spock eos

---

burnman/utils/misc.py

This PR splits the calculation of the pretty-printed values and uncertainties from the actual printing. The new function also allows the combination of value and uncertainty into standard "value(uncertainty)" notation.
This allows the values to be input more easily into a table.

split pretty print from value calculations

---

burnman/utils/chemistry.py

This PR fixes issue #620. 
re.findall fails silently on a filter (returned by `str(filter(None, site_split[1]))`)
solution_formulae doesn't seem to be used anywhere else in the codebase, so section could be removed instead of merging this PR.

Ensure not_in_site is string and not filter

---

burnman/classes/elasticsolutionmodel.py
burnman/classes/solutionmodel.py
burnman/optimize/composition_fitting.py
burnman/utils/chemistry.py

Removes `SolutionModel().solution_formulae` object and renamed `SolutionModel().formulas` to `SolutionModel().site_formulae`. 
The `SolutionModel().solution_formulae` object was originally intended to strip the sites from each site formula in the `SolutionModel` and return the chemical formulae, e.g.:
`[Mg]3[Mg0.5Si0.5]2Si3O12 -> Mg4Si4O12`
This intended use is essentially a duplication of the `Solution().endmember_formulae` object, which is itself derived from `SolutionModel().endmembers`. So the intended functionality is provided by another object.
Since writing the function, solution models have been generalised to the point that `SolutionModel().solution_formulae` might look quite different from `Solution().endmember_formulae`, but would not be as readable or contain any information …

removed solution_formulae and renamed formulas to site_formulae

---

contrib/CHRU2014/paper_incorrect_averaging.py
contrib/CHRU2014/paper_opt_pv.py
contrib/anisotropic_eos/cubic_fitting.py
contrib/anisotropic_eos/cubic_fitting_second_form.py
contrib/anisotropic_eos/cubic_fitting_second_form_atherm.py
contrib/anisotropic_eos/cubic_fitting_second_form_only_therm.py
contrib/anisotropic_eos/orthorhombic_fitting.py
contrib/anisotropic_eos/orthorhombic_fitting_second_form.py
contrib/anisotropic_plagioclase/plagioclase_model_plots.py
contrib/anisotropic_stishovite/stishovite_model_Carpenter_2000.py
contrib/anisotropic_stishovite/stishovite_model_Zhang_2021.py
contrib/anisotropic_stishovite/stishovite_model_covariance_matrix.py
contrib/anisotropic_stishovite/stishovite_model_plots.py
contrib/ipython/Create_1D_ASPECT_profile.ipynb
contrib/solution_polytope/create_FMS_pyroxene_ordering_figure.py
contrib/spock_eos/Au_comparison.py
contrib/spock_eos/fit_spock.py
examples/example_anisotropic_mineral.py
examples/example_anisotropy.py
examples/example_elastic_solution.py
examples/example_geodynamic_adiabat.py
examples/example_mineral.py
examples/example_seismic.py
examples/example_spintransition_thermal.py
tutorial/tutorial_01_material_classes.ipynb
tutorial/tutorial_03_layers_and_planets.ipynb
tutorial/tutorial_04_fitting.ipynb

set_tight_layout() has been deprecated since matplotlib 3.6. This PR replaces it with the new method, set_layout_engine('tight').

replaced set_tight_layout(True) with set_layout_engine('tight')

---

burnman/tools/polytope.py

Catch a FutureWarning from cvxpy's use of OSQP. 
The warning is benign and I don't think we can pass the appropriate OSQP argument to cvxpy's solve routine.

catch cvxpy raise_error future warning

---

burnman/classes/material.py
burnman/classes/mineral.py
burnman/eos/slb.py
burnman/tools/eos.py
misc/benchmarks/ab_initio_solids.py
test.sh
tests/test_anisotropicsolution.py
tests/test_composite.py

This PR allows minerals with P(V, T) EoSes to directly use their P(V, T) function when set_state_with_volume is called. This avoids an otherwise pointless call to brentq.
The mineral is checked to make sure that it is (a) an endmember, and that it (b) doesn't have property modifiers that might affect the equilibrium pressure.
There are a few other minor changes in this PR that are necessary to ensure that the tester still functions.

Speed up set_state_with_volume for P(V, T) minerals

---

burnman/optimize/eos_fitting.py
burnman/optimize/nonlinear_fitting.py
examples/example_fit_eos.py
examples/example_fit_eos_with_priors.py
misc/ref/example_fit_eos.py.out
misc/ref/example_fit_eos_with_priors.py.out
test.sh
tests/test_fitting.py

This PR adds the ability for users to add (potentially correlated) Gaussian priors to their parameters during nonlinear fitting.
Also included:
- Restructuring of the nonlinear fitting routines to use a model class derived from `burnman.nonlinear_fitting.NonLinearModel`. 
- A small fix to the fit_eos example (the same fix was previously applied to the fitting tutorial).
- A new example illustrating the new functionality.
- A new test covering the new functionality.

Nonlinear priors

---

tests/test_calibrants.py

This PR adds a test for the `burnman.calibrants.tools.pressure_to_pressure()` function for the case when a covariance matrix is provided.

add test for calibrant P2P covariance

---

contrib/perplex/create_phase_diagram.py
contrib/perplex/perplex_utils.py

This PR adds the option for the user to apply a polygonal mask to a Perple_X phase diagram (for example, to mask out a region at HT-LP where the SLB equation of state fails).

add optional phase diagram mask

---

burnman/eos/__init__.py
burnman/eos/anharmonic_debye_pade.py
burnman/eos/debye.py
burnman/eos/debye_temperature_models.py
burnman/eos/helper.py
burnman/eos/modular_mie_grueneisen_debye.py
tests/test_anharmonic.py
tests/test_debye.py
tests/test_modular_mgd.py

This PR adds a new modular Mie-Debye-Grueneisen (F(V, T)) equation of state.
The equation of state allows the user to pick the:
- isothermal equation of state (e.g. BM3, Vinet, SPOCK)
- model for the Debye temperature (Theta_D(V/V_0)), of which three models have been implemented.
and also allows for the addition of electronic (Bukowinski) and anharmonic (Debye-based) contributions to the Helmholtz energy.
Tests are included that cover the new functionality.

Modular Mie-Debye-Grueneisen equation of state
